service: sls-ts-template
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  explorer:
    handler: handlers.explorerHandler
    events:
      - httpApi:
          path: /graphql
          method: get
  graphQL:
    handler: handlers.graphQLHandler
    events:
      - httpApi:
          path: /graphql
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
